Added some more options to mtp-sync

diff --git a/mtp-sync b/mtp-sync
--- a/mtp-sync
+++ b/mtp-sync
@@ -14,6 +14,20 @@
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 # IN THE SOFTWARE.
 #
+
+function USAGE() {
+	echo "Usage:"
+	echo "  `basename $0` [OPTION...]"
+	echo
+	echo "Sync's a device's contents via MTP"
+	echo 
+	echo "Options:"
+	echo "  -l,--list				List known devices"
+	echo "  -m,--mode MODE			Detection mode (0=auto, 1=gvfs, 2=lsusb)"
+	echo "  -h,--help				This help screen"
+	exit
+}
+
 function REQ() {
 	(which --help >/dev/null || false) 2>/dev/null
 	if [[ "$?" != "0" ]]; then
@@ -88,61 +102,88 @@ REQ gvfs-ls gvfs-mtp
 REQ gvfs-copy gvfs-mtp
 REQ lsusb usbutils
 
-if [[ "$1" == "-m" ]]; then
-	MODE=$2
-	shift 2
-fi
+while [[ "$1" != "" ]]; do
+	case "$1" in
+		-l|--list)
+			echo -e "Device ID\tDevice Alias"
+			echo -e "---------\t------------"
+			for i in $(cat $CONFDEV); do
+				echo -e "$i\t$(cat $CONF/$i/alias)"
+				exit 5
+			done
+			shift
+			;;
+		-d|--device)
+			DEVID=$2
+			if [[ "$DEVID" == "" ]]; then
+				echo "Missing parameter for device option" >&2
+				exit 6
+			fi
+			shift 2
+			;;
+		-m|--mode)
+			MODE=$2
+			if [[ "$MODE" == "" ]]; then
+				echo "Missing parameter for mode option" >&2
+				exit 6
+			fi
+			shift 2
+			;;
+		-h|--help) 
+			USAGE
+			shift
+			;;
+		*)
+			echo "Unknown option \`$1' specified" >&2
+			exit 4
+			;;
+	esac
+done
+
 case $MODE in
 	0);;
 	1);;
 	2);;
 	*) MODE=0;;
 esac
-if [[ "$1" == "-h" ]]; then
-	echo "Usage:"
-	echo "  `basename $0` [OPTION...]"
-	echo
-	echo "Sync's a device's contents via MTP"
-	echo 
-	echo "Options:"
-	echo "  -m MODE				Detection mode (0=auto, 1=gvfs, 2=lsusb)"
-	echo "  -h					This help"
-	exit
-fi
 
 MTP=""
-if [[ "$MODE" == "0" ]]; then
-	if [[ -e $CONFDEV ]]; then
-		for i in `cat $CONFDEV`;do
-			if ( lsusb | grep -q $i ); then
-				MTP="mtp://[usb:"$( lsusb|grep $i|awk '{print $2","$4}'|sed -e 's/://')"]"
-				echo "Automatically sync'ing known device $i"
-				break
-			fi
-		done
+if [[ "$DEVID" == "" ]]; then
+	if [[ "$MODE" == "0" ]]; then
+		if [[ -e $CONFDEV ]]; then
+			for i in `cat $CONFDEV`;do
+				if ( lsusb | grep -q $i ); then
+					MTP="mtp://[usb:"$( lsusb|grep $i|awk '{print $2","$4}'|sed -e 's/://')"]"
+					echo "Automatically sync'ing known device $i"
+					break
+				fi
+			done
+		fi
 	fi
-fi
 
-if [[ "$MTP" == "" && "$MODE" != "2" ]]; then
-		# select the first MTP device detected by gvfs-mtp
-		MTP=$(gvfs-mount -li|grep MTP -A3|grep activation_root|head -n1|sed -e 's/activation_root=//' -e 's/[[:space:]]//g')
-		DEVNAME=$(gvfs-mount -li|grep MTP -B1|head -n1|sed -e 's/Volume([0-9]\+): //')
-		if [[ "$MTP" != "" ]]; then
-			echo "Automatically sync'ing device $DEVNAME detected via gvfs"
-		fi
-fi
-if [[ "$MTP" == "" ]]; then
-		echo "No device detected through gvfs or manual mode requested. Trying lsusb..." >&2
-		# manually choose from a list of connected USB devices
-		(IFS=$'\n'; j=1; for i in `lsusb`;do echo "$j) $i"; ((j++)); done)
-		echo -n "Please enter line number: "; 
-		read
-		if [[ "$(echo $REPLY|sed -e 's/[[:space:]]*//')" == "" ]]; then
-			echo "Invalid input. Aborting" >&2
-			exit 1
-		fi
-		MTP="mtp://[usb:"$( (IFS=$'\n'; j=1; for i in `lsusb`;do echo "$j) $i"; ((j++)); done)|egrep "^${REPLY}) "|awk '{print $3","$5}'|sed -e 's/://')"]"
-		DEVNAME=$( (IFS=$'\n'; j=1; for i in `lsusb`;do echo "$j) $i"; ((j++)); done)|egrep "^${REPLY}) "|sed -e 's/.\+ ID ....:.... //')
+	if [[ "$MTP" == "" && "$MODE" != "2" ]]; then
+			# select the first MTP device detected by gvfs-mtp
+			MTP=$(gvfs-mount -li|grep MTP -A3|grep activation_root|head -n1|sed -e 's/activation_root=//' -e 's/[[:space:]]//g')
+			DEVNAME=$(gvfs-mount -li|grep MTP -B1|head -n1|sed -e 's/Volume([0-9]\+): //')
+			if [[ "$MTP" != "" ]]; then
+				echo "Automatically sync'ing device $DEVNAME detected via gvfs"
+			fi
+	fi
+	if [[ "$MTP" == "" ]]; then
+			echo "No device detected through gvfs or manual mode requested. Trying lsusb..." >&2
+			# manually choose from a list of connected USB devices
+			(IFS=$'\n'; j=1; for i in `lsusb`;do echo "$j) $i"; ((j++)); done)
+			echo -n "Please enter line number: "; 
+			read
+			if [[ "$(echo $REPLY|sed -e 's/[[:space:]]*//')" == "" ]]; then
+				echo "Invalid input. Aborting" >&2
+				exit 1
+			fi
+			MTP="mtp://[usb:"$( (IFS=$'\n'; j=1; for i in `lsusb`;do echo "$j) $i"; ((j++)); done)|egrep "^${REPLY}) "|awk '{print $3","$5}'|sed -e 's/://')"]"
+			DEVNAME=$( (IFS=$'\n'; j=1; for i in `lsusb`;do echo "$j) $i"; ((j++)); done)|egrep "^${REPLY}) "|sed -e 's/.\+ ID ....:.... //')
+	fi
+else
+	MTP="mtp://[usb:"$(lsusb|grep $DEVID|awk '{print $2","$4}')"]"
 fi
 
 if [[ "$MTP" == "" ]]; then
@@ -153,11 +194,14 @@ else
 	MTP="$(echo $MTP|sed -e 's/\/*$//')"
 fi
 
-DEVID=$(lsusb | grep "$(echo $MTP | sed -e 's/.\+usb://' -e 's/\].*//' -e 's/,/ /'|awk '{print "Bus "$1" Device "$2":"}')" | awk '{print $6}')
+if [[ "$DEVID" == "" ]]; then
+	DEVID=$(lsusb | grep "$(echo $MTP | sed -e 's/.\+usb://' -e 's/\].*//' -e 's/,/ /'|awk '{print "Bus "$1" Device "$2":"}')" | awk '{print $6}')
+fi
+
 if ( ! gvfs-mount -l | grep -q $(echo "$MTP"|sed -e 's/\[/\\[/g' -e 's/\]/\\]/g') ); then
 	gvfs-mount "$MTP" >/dev/null 2>&1
 	if [[ "$?" != "0" ]]; then
-		echo "Could not access requested device using the MTP protocol. Aborting" >&2
+		echo "Could not access requested device \`$DEVID' using the MTP protocol. Aborting" >&2
 		exit 2
 	fi
 fi
